export default async (request, context) => {
  const allowedOrigins = ["https://araqque.netlify.app", "https://proxy.proxy-production.svc.cluster.local:80"];
  const origin = request.headers.get("origin");

  const headers = {
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
  };

  if (allowedOrigins.includes(origin)) {
    headers["Access-Control-Allow-Origin"] = origin;
  }

  if (request.method === "OPTIONS") {
    return new Response(null, { headers });
  }

  // Proceed with the request handling
  return context.next();
};
