[[headers]]
  for = "/*" # Matches all routes
  [headers.values]
    Access-Control-Allow-Origin = "https://araqque.netlify.app", "https://proxy.proxy-production.svc.cluster.local:80"
    Content-Type = "application/json"
